title: Tibetan Legal Texts
description: An inquiry into Tibetan Legal documents
theme: just-the-docs

url: https://daniel-wojahn.github.io/tibetan-law

aux_links:
  Original Website: https://tibetanlaw.org
